version: '2.1'
services:
  postgres:
    image: 'postgres:alpine'
    volumes:
      - ${PWD-.}/data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      PGDATA: /tmp
    ports:
      - '5432:5432'

  redis:
    image: 'redis:alpine'
    volumes:
      - ${PWD-.}/data/redis:/data
    ports:
      - '6379:6379'

  ethnode:
    image: ethereum/client-go:alpine
    volumes:
#      - ${PWD-.}/data/ethereum:/root/.ethereum
      - ${PWD-.}/config/ethereum/dev/password:/root/files/password:ro
      - ${PWD-.}/config/ethereum/dev/genesis.json:/root/files/genesis.json:ro
      - ${PWD-.}/config/ethereum/dev/keystore:/root/.ethereum/devchain/keystore:rw
    # command: --fast --cache=512 --rpcaddr 0.0.0.0
    command: --datadir=/root/.ethereum/devchain --nodekeyhex=091bd6067cb4612df85d9c1ff85cc47f259ced4d4cd99816b14f35650f59c322 --rpcapi "db,personal,eth,net,web3" --rpccorsdomain='*' --networkid=1234 --rpc --rpcaddr="0.0.0.0" init=/root/files/genesis.json --mine
    environment:
      APP_ENV: development
    ports:
      - "8545:8545"
      - "30303:30303/udp"
      - "30303:30303"

  btcnode:
    image: ruimarinho/bitcoin-core:0.15-alpine
    volumes:
      - ${PWD-.}/data/bitcoin:/home/bitcoin/data
#      - ${PWD-.}/config/bitcoin/dev/bitcoin.conf:/root/.bitcoin/bitcoin.conf:ro
    command:
      -printtoconsole
      -server=1
      -regtest=1
      -rpcuser=myuser
      -rpcpassword=mypassword
      -rpcallowip=0.0.0.0/0
      -rpcallowip=::/0
      -rpcbind=0.0.0.0
    environment:
      BITCOIN_DATA: "/home/bitcoin/data"
    ports:
      - "8332:8332"
      - "8333:8333"
      - "18332:18332"
      - "18333:18333"
      - "18444:18444"

  app:
    build: ./app
    command: python app/serve.py
    environment:
      DATABASE_NAME: "orme_development"
      DATABASE_USER: "postgres"
      DATABASE_PASSWORD: ""
      DATABASE_HOST: "postgres"
      DATABASE_PORT: "5432"
      FLASK_APP: "orme"
      FLASK_DEBUG: 1
      ORV_WALLET_ADDRESS: ""
      BITCOIN_USER: "myuser"
      BITCOIN_PASSWORD: "mypassword"
      BITCOIN_HOST: "btcnode"
      BITCOIN_PORT: 18332
      ETHEREUM_HOST: "ethnode"
      ETHEREUM_PORT: 8545
    volumes:
      - ${PWD-.}/app:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - btcnode
      - ethnode
      - contracts

  contracts:
    build: ./contracts
    volumes:
      - ${PWD-.}/contracts:/dapp
#    entrypoint: /bin/sh truffle.sh
    environment:
      RPC_HOST: "ethnode"
      RPC_PORT: 8545
    ports:
      - "8080:8080"
      - "7000:7000"
    depends_on:
      - ethnode