version: '2.1'
services:
  pyapp:
    build: ./app
    environment:
      DATABASE_NAME: "orme_development"
      DATABASE_USER: "postgres"
      DATABASE_PASSWORD: ""
      DATABASE_HOST: "postgres"
      DATABASE_PORT: "5432"
      FLASK_APP: "orme/serve.py"
      FLASK_DEBUG: 1
      # BITCOIN_ORV_WALLET: ""
      # https://blockexplorer.com/address/152f1muMCNa7goXYhYAQC61hxEgGacmncB
      BITCOIN_ORV_WALLET: "152f1muMCNa7goXYhYAQC61hxEgGacmncB"
      BITCOIN_USER: "myuser"
      BITCOIN_PASSWORD: "mypassword"
      BITCOIN_HOST: "btcnode"
      BITCOIN_PORT: 18332
      BITCOIN_WALLET_PASSPHRASE: "nopassphrase"
      ETHEREUM_HOST: "bootstrap"
      # ETHEREUM_HOST: "testrpc"
      ETHEREUM_PORT: 8545
      # ETHEREUM_NETWORK: "testrpc"
      ETHEREUM_TESTRPC_ENABLED: 1
      ETHEREUM_TESTRPC_HOST: "testrpc"
      ETHEREUM_TESTRPC_PORT: 8545
      ETHEREUM_TESTRPC_MASTER_ADDRESS: "0x22DdFe3C6439839EDF8E2e56126c65C5fc5A2f40"
      ETHEREUM_TESTRPC_SLAVE_ADDRESS: "0xa921EF355a7D2729E7674A081aeeceFf28419e23"
      REDIS_HOST: 'redis'
      REDIS_PORT: 6379
      SECRET_KEY: '7814aa5476dccd9efa87eaded6968b72d125ae0214b98e2b415820800109b803302d1064a514da3f01ff24841023ca6b5d8c1c9c9d02b496588d07aec6a55c8a'
      # ETHEREUM_PRICING_STRATEGY_CONTRACT: '0x0'
      ETHEREUM_PRICING_STRATEGY_CONTRACT: "0x57e4e6e24b956393d3d2c64c8b7665bfdc233e36"
      ETHEREUM_CONTRACT_EXECUTOR: "0x1ebd93ff2fc90b873a68e16b931a7c66e2237e31"

    volumes:
      - ${PWD-.}/app:/usr/src/app
      - ${PWD-.}/contracts/build/contracts/PricingStrategy.json:/usr/src/app/PricingStrategy.json:ro