version: '2.1'
services:
  pyapp:
    build: ./app
    environment:
      DATABASE_NAME: "orme_development"
      DATABASE_USER: "postgres"
      DATABASE_PASSWORD: ""
      DATABASE_HOST: "postgres"
      DATABASE_PORT: "5432"
      FLASK_APP: "orme/serve.py"
      FLASK_DEBUG: 1
      ORV_WALLET_ADDRESS: ""
      BITCOIN_USER: "myuser"
      BITCOIN_PASSWORD: "mypassword"
      BITCOIN_HOST: "btcnode"
      BITCOIN_PORT: 18332
      BITCOIN_WALLET_PASSPHRASE: "nopassphrase"
      ETHEREUM_HOST: "bootstrap"
      ETHEREUM_PORT: 8545
      ETHEREUM_NETWORK: "testrpc"
      # ETHEREUM_NETWORK_NAME: "development"
      REDIS_HOST: 'redis'
      REDIS_PORT: 6379
      SECRET_KEY: '7814aa5476dccd9efa87eaded6968b72d125ae0214b98e2b415820800109b803302d1064a514da3f01ff24841023ca6b5d8c1c9c9d02b496588d07aec6a55c8a'
      PRICING_STRATEGY_CONTRACT_ADDRESS: '0x0'
      CONTRACT_EXECUTOR_ADDRESS: '0x1ebd93ff2fc90b873a68e16b931a7c66e2237e31'
    volumes:
      - ${PWD-.}/app:/usr/src/app